name: Build with Maven

on:
  push:
    branches: [ main ]  # Change "main" to your main branch name if different
  pull_request:  # Optional: Trigger on pull requests

jobs:
  build:
    runs-on: ubuntu-latest  # Or another desired runner OS

    steps:
      - uses: actions/checkout@v3  # Checkout your code from the repository

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: my-app
          path: target/*.jar

      - name: Build with Maven
        run: mvn package -DskipTests  # Optionally add -DskipTests to skip tests

      # Uncomment these steps if you want to run tests:
      # - name: Run tests with Maven
      #   run: mvn test
